{% set version = "1.3" %}
{% set name = "lrcalc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.math.rutgers.edu/~asbuch/lrcalc/{{ name }}-{{ version }}.tar.gz
  sha256: 67c5131102b807b1e537da09705a9615cca56b6accae5d5f08afdf1299c72778
  patches:
    # https://bitbucket.org/asbuch/lrcalc/commits/226981a060a209efb5e0c3925b71b341b9ff63a4
    # Patch by Jeroen Demeyer to change include <vector.h> to "vector.h", plus similar cases.
    - includes.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - libtool
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - automake
    - m4
  host:

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}/symfcn.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: http://www.math.rutgers.edu/~asbuch/lrcalc/
  license: GPLv2+
  license_file: COPYING
  summary: The Littlewood-Richardson Calculator is a program designed to compute Littlewood-Richardson coefficients
  dev_url: https://bitbucket.org/asbuch/lrcalc

extra:
  recipe-maintainers:
    - isuruf
