{% set version = "2.1" %}
{% set name = "lrcalc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.math.rutgers.edu/~asbuch/lrcalc/{{ name }}-{{ version }}.tar.gz
  sha256: 996ac00e6ea8321ef09b34478f5379f613933c3254aeba624b6419b8afa5df57

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - libtool
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - automake
    - m4
  host:

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}/symfcn.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: http://www.math.rutgers.edu/~asbuch/lrcalc/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: The Littlewood-Richardson Calculator is a program designed to compute Littlewood-Richardson coefficients
  dev_url: https://bitbucket.org/asbuch/lrcalc

extra:
  recipe-maintainers:
    - isuruf
