travis:
  secure:
    BINSTAR_TOKEN: LbYrf+mmiNKqvBr8ZkziJhfrf9wG9onjRV297zHmTRSSxoPZkG8OqaFn0DJPOJygcnWAzktbdd1MPxftHD3BEBzPLhbzFD8qNMZciPjDI1G7cK4nIft65g28WrLdlffYhgqb94oC5M1OcG4QcN+ThcrR0LtWzDvBCgu2Bv1ED8UFdwHPojByDu8MEb0mU/iGMVgzEndaCz7vMttzQpOuO/iyTKsdsE2wF1jvbUjWn1hH4KpxlUV5osjPV1WUrupaSSlcVmLiFVuuI1gmSVmkME9DGfT+37vQaM7xbiv/oqi/WCU29BqLn0pXgtTD3ViJw8XEQKsUJ3+6Bciy6SQpX4ywyDfcDa99jOtMB+ySuldNceqme5buoWsvtOmZ0ECZXeeOAGwkxcH4Sns5Q/gE3d3fDSwW+wopigYYeSG10iej/O721Ss5gdsbCoU4O5mpKAVMLVy+2IrDXkC/j7LLmFEkORasbLT0usdeT1IpymBKMvwY+vOVtTQHrGnQjCo29WSEge1a7+m+cR/x1QmVLzGubyy8k0ToLP3YOH3xPCLRoiwCKL30TqRMHjWhH+h0WT6nCJ8onxdbY0+Pp53lNHqaUGUvPgp27rfAzA7vvXwO5c1VboJwkGwcv/JXQsjZb8p7f3lW0gHoXpQRIt3Nq/gmkLnNGm4N2uyWGyk73qM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
