appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: NBLINCuOUje4r1pgd1gGOk0yutyxuR5hBlbAvarHhsHJcFRANWH/jTZW7Oum2eJ95cP4Q5N5KkJIXFNhWeJha51IfNO78PcmstumpG7M3QzqgJUjqqL13RunA7ekazMK2/w/W5V+hJIigfGrzzgUwm0W9k/hBdKp7j1ofExR56sUmSvjZm2f7Mc5zRLzbV69xoqYiI4wRuMNnIqS9ugst0qoE6+UJycpwoOTtUnMgH99PyStVzxUyZyg5Cmbr83Y6NoVGgMnSrP1wAhoOiI3IcwLDGUcZhbIuPyGUF0ZhD8SCmvMzrtx0Jf7h6EWkv9TKKV5FtPMRnWd5WxpFBEx6+NQsJPTAeYzDdxRUMQus1p2Hh9gQbON1d4UcJOy6eqv/aBbQP6rj0pDVLHFpaFXZyFodhHC59VBNyjO7AqmjSmlnW3Dq740PAqlj4XkuznjNa0qubU4vUNViGFR0QbQOWEm62gSoQ2VQ8ihJachI2ISCnyG1v54JMTLI2DYuye5AxdWQ7BLuXrSeJHF2wSysZvTGNvwqZAp7AL2Z2RoXw3wZ1lrdrZaIotGXFK9gLKd9cvcUXXBiFxY0VfFCacMzEoKicw4WOjWzKRJvqXzNHUpTVHCOiLfKRVVg0S0lU3vTdNKreE/5w++OqAj3REmUzF2NQQrt7035+nA0prENCQ=}
